### ISSUE TITLE
Create Resources Table 

### ISSUE THREAD

**Issue by rhadu** [code4romania/war-support-sprijin-de-urgenta-client#104]
After resource is added from the modal it needs to be shown in a table

This applies to Products and Services Resources.

![image](https://user-images.githubusercontent.com/5412091/156451546-c7706c64-6774-4e72-8390-f9d210b01507.png)

For Mobile all products from all Resource categories need to be concatenated and shown inside a table that opens in a Modal by clicking a floating button in the bottom right corner

![image](https://user-images.githubusercontent.com/5412091/156568209-373e5f71-b489-48e6-b5b5-76d3081e9417.png)

**Comment by bogdanmosica** [comment]
I'll work on this
