### ISSUE TITLE
Update OG tags before going live

### ISSUE THREAD

**Issue by idormenco** [code4romania/war-support-sprijin-de-urgenta-client#116]
currently our <og: tags contain TBD.
We need `og:image` and text for remainging ones
```
          <meta
            property="og:image"
            content="TBD"
          />
          <meta property="og:type" content="website" />
          <meta property="og:url" content="TBD" />
          <meta property="og:site_name" content="TBD" />
          <meta property="og:title" content="TBD" />
          <meta
            property="og:description"
            content="TBD"
          />
```

**Comment by overeha** [comment]
<meta
            property="og:image"
            content="Sprijin de Urgență"
          />
          <meta property="og:type" content="website" />
          <meta property="og:url" content="www.sprijindeurgenta.ro" />
          <meta property="og:site_name" content="Sprijin de Urgență" />
          <meta property="og:title" content="Sprijin de Urgență" />
          <meta
            property="og:description"
            content="Platformă națională de management de resurse."
          />

![OG_SDU](https://user-images.githubusercontent.com/45068169/157657218-15064d0c-4f4a-4d14-be50-27bd7bcb69ff.png)
