### ISSUE TITLE
Clear user type when re-opening sign-up page

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/war-support-sprijin-de-urgenta-client#134]
Expected:
When (re)opening the sign-up page the user type field should be empty so that the user can select any item from the list

Actual:
When opening the sign-up page, the user type field is pre-filled 
The user can only select any other option, not the currently filled option 

https://user-images.githubusercontent.com/2820084/156596506-f4d6f726-7c6c-461b-9b37-cf72148f9812.mov

**Comment by cipick** [comment]
should be fixed now, can you check on staging please and close if it's resolved?

**Comment by tudoramariei** [comment]
Yes, it works ✅
