### ISSUE TITLE
[CRITICAL] Edit labels and fields in request form

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#147]
The Request flow needs to be implemented. 
Here is what every request has in the Admin dashboard as fields that need to be collected

Servicii

     Transport marfa

    - Descriere
    - Capacitate
    - Unitate de măsură (greutate) 
    - Refrigerare
    - Din județul
    - Din orașul
    - Pana în județul
    - Pana în orașul

Transport persoane

    - Descriere
    - Vehicul accesibilizat
    - Cu animal de companies
    - Din județul
   - Din orașul
   - Pana în județul
   - Pana în orașul

Voluntariat

- Tip de voluntar
- În județul 
- În orașul

Produse

- Categorie 
- Descriere
- Produs
- Numar de unități
- Unitate de măsură
- Ambalaj
- În ce județ 
- In ce oraș

Altele

- Denumire 
- In ce județ
- In ce oraș

**Comment by cipick** [comment]
will work on this

**Comment by cipick** [comment]
handover to @bogdanmosica
