### ISSUE TITLE
Sign Up - User Type Component

### ISSUE THREAD

**Issue by rhadu** [code4romania/war-support-sprijin-de-urgenta-client#15]
Implement the user type component based on the Figma design,

It should have a select and the user types are received from the backend.  

`${apiUrl}/get-donor-types/`

**Comment by dianapaula19** [comment]
I will work on this.

**Comment by rhadu** [comment]
@dianapaula19 any progress?

**Comment by dianapaula19** [comment]
@rhadu Yeah, but I still have some things to finish before creating a PR.
