### ISSUE TITLE
[Must Have] Add GDPR consent in form 

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#169]
Add the GDPR consent component in both offer and request forms.
Should be displayed on the signup page under the email and password fields. 

Text: Prin completarea formularului accept ca datele mele să fie procesate de Departamentul pentru Situații de Urgență. Cunosc faptul că Departamentul pentru Situații de Urgență prelucrează datele mele cu caracter personal în baza prevederilor Regulamentului (UE) 2016/679.*

<img width="953" alt="Screenshot 2022-03-04 at 21 36 58" src="https://user-images.githubusercontent.com/45068169/156830179-8e5b8a93-a056-4a0a-805d-86c42fe28129.png">

**Comment by cleferman** [comment]
on it
