### ISSUE TITLE
Registration - Handle non_field_errors

### ISSUE THREAD

**Issue by rhadu** [code4romania/war-support-sprijin-de-urgenta-client#170]
When user tries to sign up using a password similar to the email address the backend returns an error as `non_field_errors`

![image](https://user-images.githubusercontent.com/5412091/156830731-0f8d9f9d-0fdc-48c6-8caf-5f0f9d12365a.png)

**Comment by cleferman** [comment]
I suggest adding an ErrorComponent that show up any server errors. We can't show these as part of react-hook-form
