### ISSUE TITLE
[Critical] Fix user flows for submitting a request or an offer

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#172]
Once I have an account as an user and I choose to offer resources the form that pops up says "Resursa solicitata" while it should say "Resursa oferita". 
Please check the two flows and make sure that they behave correctly and display the right forms and fields

**Comment by bogdanmosica** [comment]
ill do it

**Comment by rhadu** [comment]
@bogdanmosica i think it was a translation error, check that as well

**Comment by cipick** [comment]
looks like is fixed
