### ISSUE TITLE
[Must Have] Add Thank you message

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#173]
After I submit a form i must receive a confirmation that my message has been sent. 

Offer form success message: 

Iți mulțumim pentru generozitate. Resursele pe care le-ai pus la dispoziție s-au înregistrat în sistem și imediat ce le vom aloca și oferi pentru a ajuta mai departe persoanele vulnerabile vom lua legătura cu tine. 

Request form success message:
Îți mulțumim pentru mesajul transmis. Vom procesa cererea ta cât de repede posibil.

**Comment by bogdanmosica** [comment]
ill do it
