### ISSUE TITLE
[Must Have] Errors in form fields

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#179]
The Select county dropdown is not working in this screen (it is the Add transport screen)
![Screenshot_20220305-023149156](https://user-images.githubusercontent.com/45068169/156859729-af166e84-c9e6-41c8-b38d-6d400a5a03ab.jpeg)

**Comment by GhenadieCebanu** [comment]
Looks like this was already fixed,
screen from develop branch:
![image](https://user-images.githubusercontent.com/3057769/156876106-8e763e3e-c8fc-48d4-bc6e-3a05fbe7adb2.png)
