### ISSUE TITLE
Sign Up - Resources 

### ISSUE THREAD

**Issue by rhadu** [code4romania/war-support-sprijin-de-urgenta-client#18]
Implement Parent Resources component based on figma design.

It should have list of offered resources selectable via checkbox

Upon selection Child components should be shown
Services Component ([issue link](https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/19))
Products Component ([issue link](https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/20))
Volunteering Component ([issue link](https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/21))
Others Component ([issue link](https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/22) )

**Comment by bogdanmosica** [comment]
I can take this, in first stage, i'll just create something basic, with todos here in there.
