### ISSUE TITLE
[Must Have] Errors in Product form fields

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#180]
We have a set of errors in the form fields. 
The county and City fields do not work at all
The three fields for unit measure, quantity and packaging do not rearrange properly on the mobile screen. 
![Screenshot_20220305-023240788](https://user-images.githubusercontent.com/45068169/156859780-d46b5a23-0c9c-4004-ba63-ac42960dad95.jpeg)

**Comment by virgilbugnariu** [comment]
I will take this.

**Comment by virgilbugnariu** [comment]
County and city fields should be functional after this PR is merged: 
https://github.com/code4romania/war-support-sprijin-de-urgenta-client/pull/177

**Comment by cleferman** [comment]
@cipick I think we can close this
