### ISSUE TITLE
[Must Have] Change SEND button in from and link with Thank you message

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#181]
Please move the SEND option on the right and at least make it Bold and a bit bigger if not a button. 
Please link this with Issus #173 
![Screenshot_20220305-023522394](https://user-images.githubusercontent.com/45068169/156859866-5df49ce1-ac40-4201-bd54-2607049fb600.jpeg)

**Comment by idormenco** [comment]
on it

**Comment by idormenco** [comment]
this buttons seems to be temporary in code they are marked with remove.
@cipick please advice

**Comment by cipick** [comment]
Yes @idormenco , they are meant ollnly for testing. The final flow will use 'next step' button to submit the forms
