### ISSUE TITLE
[Must Have] Create About page and add it to the main menu

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#182]
Create an about page for [this link](http://sprijin-de-urgenta.heroesof.tech.s3-website-eu-west-1.amazonaws.com/despre-proiect/) 
Simple static page with text and images

The text is: 

În situații de criză este esențial ca resursele utile să ajungă la cei care au cea mai mare nevoie de ele în cel mai simplu și eficient mod cu putință. Populația care fuge acum din calea unui conflict terifiant are nevoie de tot sprijinul pe care România îl poate pune la dispoziție în cel mai scurt timp. 

Platforma Sprijin de Urgență este un sistem integrat de management al resurselor pe care societatea civilă și toate persoanele fizice și juridice le pot aduce împreună pentru a ajuta în situații critice. În funcție de nevoile curente, alege una dintre variantele de mai jos. Sprijin de Urgență este un proiect dezvoltat de Code for Romania în parteneriat cu Guvernul României și Departamentul de Situații de Urgență pentru administrarea de resurse și nevoi în momente de criză.

The logos are: 
- Code for Romania logo
- Government logo
- DSU logo
- IOM
- UNHCR

remove CNRR logo

Model
https://dopomoha.ro/ro/despre

**Comment by SergiuPintilei** [comment]
fac eu asta
