### ISSUE TITLE
Sign Up - Resources - Products Component

### ISSUE THREAD

**Issue by rhadu** [code4romania/war-support-sprijin-de-urgenta-client#20]
Implement the Products Component with the required form

When adding a product via the plus sign the respective form section should be cleared 

After adding a product : 
- On desktop A product table should appear on the right side 
- On mobile A button should appear in the bottom right corner which on clicking should expand a modal full screen transitioning from bottom to top.

The Products component should be a child of Resources Component

**Comment by virgilbugnariu** [comment]
I'll take this.

**Comment by rhadu** [comment]
After the PR associated with #55 is merged it can implemented on this as well.

A draft implementation is done for Services Form
