### ISSUE TITLE
Remove table from request forms

### ISSUE THREAD

**Issue by cipick** [code4romania/war-support-sprijin-de-urgenta-client#240]

**Comment by rhadu** [comment]
Can't a user request for more products? 
And before pressing the final step button isn't it better to see again what products he requested?

**Comment by cipick** [comment]
@overeha said no. ideally when the user clicks 
`Add` button and modal is closed it should submit the form too (like he automatically clicks `Next step` button). 
Tried this yesterday but first product i added was not sent, just the second one. 
![Screenshot 2022-03-07 at 12 09 31](https://user-images.githubusercontent.com/6429818/157010967-f7c14f3f-8eeb-4f8e-a610-c98ac7309cd2.png)

I guess it could work if i would wrap `handleSubmit` with `useCallback`
![Screenshot 2022-03-07 at 12 06 44](https://user-images.githubusercontent.com/6429818/157010575-bc522bb4-a91c-44ee-87b7-375ec1a56310.png)

**Comment by costinicolescu** [comment]
I will try to fix it.

**Comment by costinicolescu** [comment]
Looks like what you discussed here was fixed in another [PR](https://github.com/code4romania/war-support-sprijin-de-urgenta-client/pull/287/commits/ccf7dec453f82877d9b9103eadf579531f6fcfe2)
