### ISSUE TITLE
Invalidate only input ?

### ISSUE THREAD

**Issue by idormenco** [code4romania/war-support-sprijin-de-urgenta-client#272]
When submitting an empty form labels and inputs are invalidated (red-colored) and it looks a little too much 
![image](https://user-images.githubusercontent.com/1877190/157085748-b56bbbb0-2709-48e2-99d3-0823b93ccd54.png)

**Comment by rhadu** [comment]
I suggest that we keep the label intact and don't make it red

**Comment by SergiuPintilei** [comment]
agree. will remove it from label

**Comment by idormenco** [comment]
@SergiuPintilei all yours
