### ISSUE TITLE
Validation for "How much time can you spend on these activities?" on Passenger transportation

### ISSUE THREAD

**Issue by idormenco** [code4romania/war-support-sprijin-de-urgenta-client#273]
When filling Passenger transportation form 
dropdown for `How much time can you spend on these activities?` is not validated and allows empty value to be sent.

this will break on server side with 
![image](https://user-images.githubusercontent.com/1877190/157086300-32edff73-8b68-41f9-b9d4-107b5490d657.png)

**Comment by GhenadieCebanu** [comment]
i can take this
