### ISSUE TITLE
[Products] Tents form redesign

### ISSUE THREAD

**Issue by idormenco** [code4romania/war-support-sprijin-de-urgenta-client#286]
Redesing and rearange form 
![image](https://user-images.githubusercontent.com/1877190/157107425-6568858e-c2d8-4307-b807-c304dc2aa030.png)

**Comment by SergiuPintilei** [comment]
<img width="581" alt="Screenshot 2022-03-08 at 14 10 46" src="https://user-images.githubusercontent.com/17024662/157235772-b60c2777-1802-4dea-8b47-330c7ae9590a.png">
Putem pune in label sau in placeholder. cum vreti?

**Comment by idormenco** [comment]
@SergiuPintilei hai sa punem doar in placeholder

**Comment by SergiuPintilei** [comment]
opened a pr. dunno why the validation message doesn't show up :-? ...aded rules to be integer and positive
