### ISSUE TITLE
[Suggestion] Small Improvement - use Required comp

### ISSUE THREAD

**Issue by SergiuPintilei** [code4romania/war-support-sprijin-de-urgenta-client#298]
Noticed that we have ```{required && <Required />}``` logic to display an asterisk (*) in our controls. I would suggest to pass ```required``` to all of comps that have this validation

Make it red **only** if errors are present tho

**Comment by cleferman** [comment]
I'm not sure I understand, do you suggest passing required like this `<Required required />` instead of conditionally rendering the comp?

Also, I would keep the asterisk red at all times, it's red in most apps. Usually, client validation errors will show right beneath the validated. (Server validation errors will show in a different component, but we should update the client validatiosn as soon as we see them popping up)

**Comment by SergiuPintilei** [comment]
no I mean to look in our forms and where a field has required validation in Yup schema, add "required" prop to corresponding form control. e.g. if name is required... ```<Input
            required
            type="text"
            errors={errors.name}
            label="Name"
            {...register('name')}
          />```

**Comment by SergiuPintilei** [comment]
we have the ```{required && <Required />``` check in our form controls implementation, but almost nowhere the ```required``` prop is passed in

**Comment by SergiuPintilei** [comment]
and regarding the red-grey thingie...now it will be red even if we don't have an error. that's what I wanted to say by that: gray until submit...make it red if error

**Comment by cleferman** [comment]
> we have the `{required && <Required />` check in our form controls implementation, but almost nowhere the `required` prop is passed in
I agree we have to pass down the required prop can you create an issue?

> and regarding the red-grey thingie...now it will be red even if we don't have an error. that's what I wanted to say by that: gray until submit...make it red if error
I guess we can keep the discussion open but the main reason the asterisk is red even when you don't have errors is to make it more visible, so the user doesn't just go past it.

**Comment by SergiuPintilei** [comment]
started to add required, but faced another thing:
<img width="1440" alt="Screenshot 2022-03-09 at 08 11 34" src="https://user-images.githubusercontent.com/17024662/157383224-bcaa3812-1768-466d-8b12-fb9fb41f5529.png">
we currently pass ```required={required}``` to native html elements, so in this case native required validation will show up before our red messages. 

what is the approach we want?

**Comment by cleferman** [comment]
I vote against the native one. I think that adds some a11y functionalities as well but c'est la vie
