### ISSUE TITLE
User can't go back

### ISSUE THREAD

**Issue by idormenco** [code4romania/war-support-sprijin-de-urgenta-client#350]
**steps to reproduce:**
1. enter sprijindeurgenta website
2. pick offer
3. pick services in `I want to help with:`
4. user is on `sign-up/offer/`
**Expected:** 
user should be able to go back from this screen to change selection from `I want to help with:`
**Actual:**
Browser back button does not work and user is stuck (no other buttons are available) .
Only way is to press on the logo and restart flow

**Comment by rhadu** [comment]
i'll take it
