### ISSUE TITLE
Add banner with link in page

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-sprijin-de-urgenta-client#373]
The task is as follows.
(1) create a new category in the admin dashboard called “Solicitari mancare ONG”
(2) create a form with [the fields specified in this document](https://docs.google.com/document/d/1H3cISkMA8UchHfJjMfBOJ0YIJoZ8F0kMdj-SauRURMY/edit?usp=sharing)
(3) publish the form (it can be the classic Django format like the one [we have here for example](https://app.ukrainechildcancerhelp.ro/ro/cerere-pacient/)) on a the link [sprijindeurgenta.ro/solicitari-mancare](http://sprijindeurgenta.ro/solicitari-mancare) or if that does not work, on [solicitari.sprijindeurgenta.ro](http://solicitari.sprijindeurgenta.ro/)
(4) these requests do not need to be allocated, the DSU just needs to see them in the dashboard and set their status to “in progress/solved/rejected”. That is all.
(4) also need someone to help me add a stripe/banner [in this page](https://sprijindeurgenta.ro/request/) on the public website to link the form in it

This task addresses point 4 of this list

<img width="826" alt="Screenshot 2022-08-27 at 10 35 47" src="https://user-images.githubusercontent.com/45068169/187028727-dac8949d-9dfd-49b2-ad7b-3ee27cab8fc2.png">

**Comment by ramadanomar** [comment]
- [x] 🙋 I would be interested in resolving this bug.
