### ISSUE TITLE
Link Sign Up user with Backend

### ISSUE THREAD

**Issue by rhadu** [code4romania/war-support-sprijin-de-urgenta-client#59]
Using axios (or opened to suggestions) sign up user using the details from the form.
The received token should be saved in cookies for future api calls

`{api}/auth/signup/` It still needs to be implemented
http://sprijin-de-urgenta-api.heroesof.tech:8070/api/v1/schema/swagger-ui/

**Comment by okonet** [comment]
Maybe consider using https://next-auth.js.org to handle the flow and auth on the client.

**Comment by rhadu** [comment]
That's a very good idea. If you have experience with it you can take this issue. Although we'll have to wait for the sign up to be implemented
